server:
  port: 8080
spring:
  h2: # http://localhost:8081/h2-console
    console:
      enabled: true
      settings:
        web-allow-others: true # for remote access  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
